name = "granite-workers"
main = "workers/instagram-webhook/src/index.ts"
compatibility_date = "2026-05-16"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "granite_v2"
database_name = "granite-v2"
database_id = "086073b7-4369-47ea-baf6-2b76de860620"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "granite-v2"
